### ISSUE TITLE
No "Name" scheme should be accepted

### ISSUE THREAD

**Issue by talexie** [pepfar-datim/datimvalidation-web#5]
No "Name" scheme should be accepted and should not appear in the options for ID,data Element or org Unit schemes. Names usually not unique when users include them in the files.

**Comment by jason-p-pickering** [comment]
@vshioshvili do you agree with this feature request? If so, I can make this change.

**Comment by jason-p-pickering** [comment]
After receiving a few SIMS related files where the "name" is used for data elements, I do not think we should proceed with this. Names should be able to be used, although I agree with you @talexie it may not always be the best choice. Nonetheless, I think we should continue to support this coding scheme.
